"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/Button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/Card"
import { Badge } from "@/components/ui/Badge"
import { Modal } from "@/components/ui/Modal"
import {
  FileText,
  Search,
  UploadCloud,
  Filter,
  FileCheck,
  Calendar,
  User,
  ArrowRight,
  Download,
  FileSearch,
  Plus
} from "lucide-react"

export default function DocumentsPage() {
  const [searchTerm, setSearchTerm] = useState("")
  const [selectedType, setSelectedType] = useState("all")

  const documents = [
    {
      id: "DOC-1092",
      title: "Comprehensive Metabolic & Lipid Panel.pdf",
      type: "Lab Panel",
      patient: "Sarah Jenkins",
      date: "2026-03-16",
      size: "1.4 MB",
      status: "Analyzed",
    },
    {
      id: "DOC-1091",
      title: "Inpatient Cardiology Discharge Summary.pdf",
      type: "Discharge Summary",
      patient: "John Doe",
      date: "2026-03-15",
      size: "820 KB",
      status: "Analyzed",
    },
    {
      id: "DOC-1090",
      title: "Chest Radiography Report - PA & Lateral.pdf",
      type: "Radiology Report",
      patient: "Emily Watson",
      date: "2026-03-12",
      size: "3.1 MB",
      status: "Verified",
    },
    {
      id: "DOC-1089",
      title: "Endocrinology Outpatient Progress Note.pdf",
      type: "Clinical Note",
      patient: "Robert Chen",
      date: "2026-03-10",
      size: "540 KB",
      status: "Analyzed",
    },
  ]

  const filtered = documents.filter((doc) => {
    const matchesSearch =
      doc.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      doc.patient.toLowerCase().includes(searchTerm.toLowerCase()) ||
      doc.id.toLowerCase().includes(searchTerm.toLowerCase())

    const matchesType = selectedType === "all" || doc.type === selectedType

    return matchesSearch && matchesType
  })

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#090d16] text-slate-900 dark:text-slate-100 transition-colors">
      
      {/* Header */}
      <div className="border-b border-slate-200/80 dark:border-slate-800 bg-white/90 dark:bg-slate-950/90 backdrop-blur-md px-6 py-6">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Link href="/dashboard" className="text-xs text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition">
                Workspace
              </Link>
              <span className="text-slate-300 dark:text-slate-700">/</span>
              <span className="text-xs font-semibold text-emerald-600 dark:text-emerald-400">Documents</span>
            </div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
              Clinical Document Intelligence
            </h1>
          </div>

          <Link href="/diagnostics/analyze">
            <Button variant="primary" size="sm" icon={UploadCloud}>
              Upload New Medical PDF
            </Button>
          </Link>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-6">
        
        {/* Document Ingestion Spotlight Banner */}
        <div className="rounded-3xl border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm overflow-hidden grid grid-cols-1 lg:grid-cols-12 items-center">
          <div className="lg:col-span-4 h-48 lg:h-52 relative overflow-hidden group">
            <img
              src="/clinical_radiology_scan.jpg"
              alt="Clinical Radiology and Tomography Reading Suite"
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
            />
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-transparent to-white dark:to-slate-900 hidden lg:block" />
          </div>
          <div className="lg:col-span-8 p-6 sm:p-8 space-y-2">
            <div className="inline-flex items-center gap-2 px-2.5 py-0.5 rounded-md bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 text-[11px] font-bold uppercase tracking-wider">
              <span>Multimodal Diagnostic Ingestion</span>
            </div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">Radiology, Lab Panels & Discharge Summaries</h2>
            <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 leading-relaxed max-w-2xl">
              OCR-accelerated clinical document indexing with verbatim citation tracking. Every hypothesis generated by Prakriti is tied back to exact source text and hospital imaging interpretations.
            </p>
          </div>
        </div>

        {/* Search & Filter Bar */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 p-4 rounded-2xl border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm">
          <div className="relative w-full sm:w-80">
            <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search document title, patient..."
              className="w-full pl-10 pr-4 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-xs text-slate-900 dark:text-white placeholder-slate-400 focus:outline-none focus:border-emerald-500"
            />
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <span className="text-xs font-semibold text-slate-500">Document Type:</span>
            {["all", "Lab Panel", "Discharge Summary", "Radiology Report"].map((type) => (
              <button
                key={type}
                onClick={() => setSelectedType(type)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold capitalize transition ${
                  selectedType === type
                    ? "bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900"
                    : "bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200"
                }`}
              >
                {type === "all" ? "All Documents" : type}
              </button>
            ))}
          </div>
        </div>

        {/* Document Cards / Table */}
        <Card className="overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 dark:bg-slate-950/60 border-b border-slate-100 dark:border-slate-800 text-slate-500 font-semibold uppercase tracking-wider">
                <tr>
                  <th className="px-6 py-3.5">Document Name</th>
                  <th className="px-6 py-3.5">Record ID</th>
                  <th className="px-6 py-3.5">Document Type</th>
                  <th className="px-6 py-3.5">Associated Patient</th>
                  <th className="px-6 py-3.5">Ingestion Date</th>
                  <th className="px-6 py-3.5">File Size</th>
                  <th className="px-6 py-3.5 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {filtered.map((doc) => (
                  <tr key={doc.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/40 transition">
                    <td className="px-6 py-4 font-bold text-slate-900 dark:text-white flex items-center gap-2.5">
                      <FileText className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
                      <span className="truncate max-w-xs">{doc.title}</span>
                    </td>
                    <td className="px-6 py-4 font-mono text-slate-500">{doc.id}</td>
                    <td className="px-6 py-4 font-medium text-slate-700 dark:text-slate-300">
                      {doc.type}
                    </td>
                    <td className="px-6 py-4 text-slate-600 dark:text-slate-400">
                      {doc.patient}
                    </td>
                    <td className="px-6 py-4 text-slate-500 font-mono">
                      {doc.date}
                    </td>
                    <td className="px-6 py-4 text-slate-500">
                      {doc.size}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <Link
                        href="/diagnostics/analyze"
                        className="inline-flex items-center gap-1 font-semibold text-emerald-600 dark:text-emerald-400 hover:underline"
                      >
                        <span>Open In Triage</span>
                        <ArrowRight className="w-3.5 h-3.5" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

      </div>
    </div>
  )
}
